/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TP1;

import java.awt.GridLayout;

import javax.swing.JFrame;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

 // this main method should actually be placed in another class (it's here just to avoid having multiple files)
    public static void main(String[] a) {
    		JFrame window = new JFrame();
    		window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    		window.setBounds(30, 30, 400, 400);
    		
    		// Create an instance of the model
            // Model model;
            
            // Maybe put some data in the model
    		int oldFirst = 0;
    		int oldLast = 0;

    		// Create the controller and the view and link all together
    				
    		
    		// display layout
    		GridLayout layout = new GridLayout(1, 2);

    		window.getContentPane().add(controller.getView());
    		
    		window.setLayout(layout);
    		window.pack();
    		window.setVisible(true);
    		// window.pack();
    	}
}
